name: Deploy Solidity Smart Contract

on:
  push:
    branches: [ main ]
    paths:
      - packages/evm/solidity/**
      - .github/workflows/deploy-evms.yml
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]
        
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci
      working-directory: packages/evm

    - name: Install dependencies
      run: npm ci
      working-directory: packages/evm/solidity

    - name: Compile contracts
      run: npx hardhat compile
      working-directory: packages/evm/solidity
      
    # - name: Run tests
    #   run: npx hardhat test
    
    # deploy eth contracts
    - name: Deploy ETH to Sepolia testnet
      run: npx hardhat run scripts/deployETH.js --network sepolia
      working-directory: packages/evm/solidity
      continue-on-error: true
    
    - name: Deploy ETH to Optimism Sepolia testnet
      run: npx hardhat run scripts/deployETH.js --network optimismSepolia
      working-directory: packages/evm/solidity
      continue-on-error: true

    - name: Deploy ETH to Arbitrum Sepolia testnet
      run: npx hardhat run scripts/deployETH.js --network arbitrumSepolia
      working-directory: packages/evm/solidity
      continue-on-error: true

    - name: Deploy ETH to Linea Sepolia testnet
      run: npx hardhat run scripts/deployETH.js --network lineaSepolia
      working-directory: packages/evm/solidity
      continue-on-error: true

    - name: Deploy ETH to Taiko Hekla testnet
      run: npx hardhat run scripts/deployETH.js --network taikoHekla
      working-directory: packages/evm/solidity
      continue-on-error: true
    
    - name: Deploy ETH to Immutable Testnet
      run: npx hardhat run scripts/deployETH.js --network immutableTestnet
      working-directory: packages/evm/solidity
      continue-on-error: true

    # deploy erc20 contracts
    - name: Deploy ERC20 to Sepolia testnet
      run: npx hardhat run scripts/deployERC20.js --network sepolia
      working-directory: packages/evm/solidity
      continue-on-error: true
    
    - name: Deploy ERC20 to Optimism Sepolia testnet
      run: npx hardhat run scripts/deployERC20.js --network optimismSepolia
      working-directory: packages/evm/solidity
      continue-on-error: true

    - name: Deploy ERC20 to Arbitrum Sepolia testnet
      run: npx hardhat run scripts/deployERC20.js --network arbitrumSepolia
      working-directory: packages/evm/solidity
      continue-on-error: true

    - name: Deploy ERC20 to Linea Sepolia testnet
      run: npx hardhat run scripts/deployERC20.js --network lineaSepolia
      working-directory: packages/evm/solidity
      continue-on-error: true

    - name: Deploy ERC20 to Taiko Hekla testnet
      run: npx hardhat run scripts/deployERC20.js --network taikoHekla
      working-directory: packages/evm/solidity
      continue-on-error: true
    
    - name: Deploy ERC20 to Immutable Testnet
      run: npx hardhat run scripts/deployERC20.js --network immutableTestnet
      working-directory: packages/evm/solidity
      continue-on-error: true